var CONFIG = {
  ADMIN_EMAIL: "chleba.objednavky@gmail.com",
  ADMIN_TOKEN: "REPLACE_WITH_UUID",
  SHEET_ID: "REPLACE_WITH_SHEET_ID",
  WEEKS_AHEAD: 8,
  DEFAULT_BAKING_DAY: 5, // 5 = pátek (1=Po, 7=Ne)
  ORDER_CUTOFF_HOUR: 16,
  DEPLOYMENT_URL: "REPLACE_WITH_DEPLOYMENT_URL",
};
